Fix a couple of problems from the restructuring to make the tests run

diff --git a/run_unittests b/run_unittests
--- a/run_unittests
+++ b/run_unittests
@@ -4,8 +4,105 @@
 ## See the file LICENCE for copying conditions.
 
 set -e
+
+### Traps and shopts:
+
+
+
+## {{{ test functions
+
+gpg_bash_lib_function_unit_test_check_error_handler() {
+   gpg_bash_lib_unit_test_current_trap="$(trap -p ERR)"
+   true "gpg_bash_lib_unit_test_existing_trap_original: $gpg_bash_lib_unit_test_existing_trap_original"
+   true "gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib: $gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib"
+   true "gpg_bash_lib_unit_test_current_trap   : $gpg_bash_lib_unit_test_current_trap"
+   if [ ! "$gpg_bash_lib_unit_test_existing_trap_original" = "$gpg_bash_lib_unit_test_current_trap" ]; then
+      echo "ERROR #1 !" >&2
+      exit 1
+   fi
+   if [ ! "$gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib" = "$gpg_bash_lib_unit_test_current_trap" ]; then
+      echo "ERROR #2 !" >&2
+      exit 1
+   fi
+}
+
+## }}}
+
+## {{{ setup
+
+gpg_bash_lib_function_unit_test_error_handler() {
+   echo "$FUNCNAME ERROR #0 !" >&2
+   exit 1
+}
+
+trap "gpg_bash_lib_function_unit_test_error_handler" ERR
+gpg_bash_lib_unit_test_existing_trap_original="$(trap -p ERR)"
+
+set -o errtrace
+
+## }}}
+
+## {{{ test 1
+
+source "./gpg-bash"
+
+trap "gpg_bash_lib_function_unit_test_error_handler" ERR
+gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib="$(trap -p ERR)"
+
+gpg_bash_lib_function_init
+
+gpg_bash_lib_function_deinit
+
+gpg_bash_lib_function_unit_test_check_error_handler
+
+## pipefail was not set before, it should not be set now.
+
+if test -o pipefail ; then
+   echo "ERROR #4!" >&2
+   exit 1
+fi
+
+## }}}
+
+## {{{ test 2
+
 set -o pipefail
 set -o errtrace
+
+source "./gpg-bash"
+
+gpg_bash_lib_function_init
+
+gpg_bash_lib_function_deinit
+
+gpg_bash_lib_unit_test_current_trap="$(trap -p ERR)"
+
+gpg_bash_lib_function_unit_test_check_error_handler
+
+## errtrace, pipefail was set before, it should be set now.
+
+if ! test -o errtrace ; then
+   echo "ERROR #5 !" >&2
+   exit 1
+fi
+
+if ! test -o pipefail ; then
+   echo "ERROR #6 !" >&2
+   exit 1
+fi
+
+## }}}
+
+gpg_bash_lib_function_unit_test_custom_error_handler() {
+   true "$FUNCNAME: functional"
+}
+
+gpg_bash_lib_input_error_handler_extra="gpg_bash_lib_function_unit_test_custom_error_handler ; return 0"
+
+gpg_bash_lib_function_error_handler
+
+true "SUCCESS!"
+
 
 
 
@@ -40,7 +137,7 @@ gpg_bash_lib_function_unit_test_genkey() {
       Subkey-Length: 1024
       Name-Real: auto generated test key for unit test
       Name-Email: unit@test.key
-      Expire-Date: 2020-12-12
+      Expire-Date: 2022-12-12
       Preferences: SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 ZLIB BZIP2 ZIP Uncompressed
    " | faketime -f "-61d" \
          gpg \
@@ -169,104 +266,3 @@ gpg_bash_lib_function_unit_test_testrun_3
 gpg_bash_lib_function_unit_test_testrun_4
 
 
-
-### Traps and shopts:
-
-
-
-## {{{ test functions
-
-gpg_bash_lib_function_unit_test_check_error_handler() {
-   gpg_bash_lib_unit_test_current_trap="$(trap -p ERR)"
-   true "gpg_bash_lib_unit_test_existing_trap_original: $gpg_bash_lib_unit_test_existing_trap_original"
-   true "gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib: $gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib"
-   true "gpg_bash_lib_unit_test_current_trap   : $gpg_bash_lib_unit_test_current_trap"
-   if [ ! "$gpg_bash_lib_unit_test_existing_trap_original" = "$gpg_bash_lib_unit_test_current_trap" ]; then
-      echo "ERROR #1 !" >&2
-      exit 1
-   fi
-   if [ ! "$gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib" = "$gpg_bash_lib_unit_test_current_trap" ]; then
-      echo "ERROR #2 !" >&2
-      exit 1
-   fi
-}
-
-## }}}
-
-## {{{ setup
-
-gpg_bash_lib_function_unit_test_error_handler() {
-   echo "$FUNCNAME ERROR #0 !" >&2
-   exit 1
-}
-
-trap "gpg_bash_lib_function_unit_test_error_handler" ERR
-gpg_bash_lib_unit_test_existing_trap_original="$(trap -p ERR)"
-
-set -o errtrace
-
-## }}}
-
-## {{{ test 1
-
-# Debug:
-pwd
-
-source "./gpg-bash"
-
-trap "gpg_bash_lib_function_unit_test_error_handler" ERR
-gpg_bash_lib_unit_test_existing_trap_by_gpg_bash_lib="$(trap -p ERR)"
-
-gpg_bash_lib_function_init
-
-gpg_bash_lib_function_deinit
-
-gpg_bash_lib_function_unit_test_check_error_handler
-
-## pipefail was not set before, it should not be set now.
-
-if test -o pipefail ; then
-   echo "ERROR #4!" >&2
-   exit 1
-fi
-
-## }}}
-
-## {{{ test 2
-
-set -o pipefail
-set -o errtrace
-
-source "./gpg-bash"
-
-gpg_bash_lib_function_init
-
-gpg_bash_lib_function_deinit
-
-gpg_bash_lib_unit_test_current_trap="$(trap -p ERR)"
-
-gpg_bash_lib_function_unit_test_check_error_handler
-
-## errtrace, pipefail was set before, it should be set now.
-
-if ! test -o errtrace ; then
-   echo "ERROR #5 !" >&2
-   exit 1
-fi
-
-if ! test -o pipefail ; then
-   echo "ERROR #6 !" >&2
-   exit 1
-fi
-
-## }}}
-
-gpg_bash_lib_function_unit_test_custom_error_handler() {
-   true "$FUNCNAME: functional"
-}
-
-gpg_bash_lib_input_error_handler_extra="gpg_bash_lib_function_unit_test_custom_error_handler ; return 0"
-
-gpg_bash_lib_function_error_handler
-
-true "SUCCESS!"
