WIP, first complete example, version for peer review

diff --git a/examples/example_verify_bitcoind b/examples/example_verify_bitcoind
--- a/examples/example_verify_bitcoind
+++ b/examples/example_verify_bitcoind
@@ -2,7 +2,11 @@
 
 ## See the file LICENCE for copying conditions.
 
+# This is an example showing how gpg-bash can be used to validate the signatures of the Bitcoin Core source code.
 # This script assumes that you have already downloaded trusted public keys and saved them to $bitcoind_keys_folder
+# getting trustworthy gpg keys are thus outside the scope of this script.
+# You can specify keys that you trust (that must verify) and in addition to these specify a number of additional keys
+# that must also verify.
 
 # Settings
 bitcoind_version="22.0"
@@ -11,19 +15,27 @@ bitcoind_keys_folder="bitcoind-pub-keys"
 bitcoind_data_file="${bitcoind_folder}/bitcoin-${bitcoind_version}-x86_64-linux-gnu.tar.gz"
 bitcoind_SHA256_file="${bitcoind_folder}/SHA256SUMS"
 bitcoind_sig_file="${bitcoind_folder}/SHA256SUMS.asc"
+bitcoind_maximum_age_in_seconds=31104000    # We accept signature up to one year after signing, to validate releases
+                                            # older than this  increase this value accordingly.
 
 
 # Key trust settings
 #   The verification will fail unless all keys listed in $bitcoind_trusted_key_hashes check out
 #   The script will ignore verifying keys listed in $bitcoind_untrusted_key_hashes
-#   From the remaining keys (all keys - trusted keys - untrusted keys) at least $bitcoind_acceptable_fails number of keys needs to check out
-bitcoind_trusted_key_hashes="152812300785C96444D3334D17565732E08E5E41 D1DBF2C4B96F2DEBF4C16654410108112E7EA81F CFB16E21C950F67FA95E558F2EEB9F5CC09526C1"
-bitcoind_untrusted_key_hashes="0CCBAAFD76A2ECE2CCD3141DE2FFD5B1D88CA97D"
+#   From the remaining keys (all keys - trusted keys - untrusted keys) at least $bitcoind_min_confirm number
+#   of keys needs to check out
+bitcoind_trusted_key_hashes=( "152812300785C96444D3334D17565732E08E5E41" "D1DBF2C4B96F2DEBF4C16654410108112E7EA81F" "CFB16E21C950F67FA95E558F2EEB9F5CC09526C1" )
+bitcoind_untrusted_key_hashes=( "0CCBAAFD76A2ECE2CCD3141DE2FFD5B1D88CA97D" )
 bitcoind_min_confirm=4
 
+
 # Output deciding variables (not settings):
+declare -a trusted_used=()
+declare -a confirmed_used=()
 trusted=0
 confirmed=0
+total=0
+
 
 # Downloads a file if it does not already exist, exits if the download fails
 # Usage:
@@ -88,7 +100,7 @@ bitcoind_begin() {
 }
 
 
-## Split the signatures in the .asc file and each for verification
+## Split the .asc file into the individual signatures and verify each
 bitcoind_verification() {
     echo "$FUNCNAME: BEGIN"
 
@@ -122,17 +134,13 @@ verify_signature() {
 
     # Save the output in a temporary signature file containing only one signature
     tmp_signature_file=$(mktemp /tmp/verify_bitcoind.XXXXXX)
-    # echo "Debug:"
-    # printf "%u\n$2" $1
-    # echo "\$2=" "$2"
-    # echo "\$tmp_signature_file=$tmp_signature_file"
     echo "$2" > $tmp_signature_file
-    # cat $tmp_signature_file
 
     ## Set up gpg-bash
     gpg_bash_lib_input_key_import_dir=$bitcoind_keys_folder
-    gpg_bash_lib_input_file_name_enforce="true"
+    gpg_bash_lib_input_file_name_enforce="false"
     gpg_bash_lib_input_cleanup="true"
+    gpg_bash_lib_input_maximum_age_in_seconds=31104000    # We accept signature up to one year after signing, to validate older releases increase this value accordingly.
     gpg_bash_lib_input_data_file=$bitcoind_SHA256_file    # We are actually not verifying the archive but the only the SHA256SUMS file here
     gpg_bash_lib_input_sig_file=$tmp_signature_file
 
@@ -150,53 +158,77 @@ verify_signature() {
 bitcoind_check_output() {
     echo "$FUNCNAME: BEGIN"
 
-    ## This is an example on how you can access variables, that gpg-bash has
-    ## set for you. There are more variables available. Those are listed in
-    ## the documentation.
+    # Check if it is among our untrusted keys, if it is we just move on and dont count it either towards a failure or success:
+    if [[ " ${bitcoind_untrusted_key_hashes[*]} " =~ " ${gpg_bash_lib_output_fingerprint_in_hex} " ]]; then
+        echo "Ignoring untrusted key."
+    else
 
-    echo "\
-gpg_bash_lib_output_failure_status: $gpg_bash_lib_output_failure_status
-gpg_bash_lib_output_gpg_verify_exit_code: $gpg_bash_lib_output_gpg_verify_exit_code
-gpg_bash_lib_output_validsig_status: $gpg_bash_lib_output_validsig_status
-gpg_bash_lib_output_fingerprint_in_hex: $gpg_bash_lib_output_fingerprint_in_hex
-gpg_bash_lib_output_signed_on_unixtime: $gpg_bash_lib_output_signed_on_unixtime
-gpg_bash_lib_output_signed_on_date: $gpg_bash_lib_output_signed_on_date
-gpg_bash_lib_output_notation[$"file@name"]: ${gpg_bash_lib_output_notation[$"file@name"]}
-gpg_bash_lib_output_file_name_tampering: $gpg_bash_lib_output_file_name_tampering
-gpg_bash_lib_output_freshness_status: $gpg_bash_lib_output_freshness_status
-gpg_bash_lib_output_freshness_detail: $gpg_bash_lib_output_freshness_detail
-gpg_bash_lib_output_freshness_msg:
-$gpg_bash_lib_output_freshness_msg
-gpg_bash_lib_output_alright_status: $gpg_bash_lib_output_alright_status"
+        # Check if the signature was validated
+        if [ "$gpg_bash_lib_output_validsig_status" = "true" ]; then
+            echo "Signature by key $gpg_bash_lib_output_fingerprint_in_hex was validated OK"
 
-    # TODO: Find a way to check the key fingerprint that was used to sign the signature
+            # Check if it is one of our trusted keys:
+            if [[ " ${bitcoind_trusted_key_hashes[*]} " =~ " ${gpg_bash_lib_output_fingerprint_in_hex} " ]]; then
 
-    # if in bitcoind_untrusted_key_hashes
-    #    ignore
-    # else
-    #    if signature valid
-    #       if in bitcoind_trusted_key_hashes
-    #           trusted++
-    #       else
-    #           confirmed++
-    #       fi
-    #    fi
-    # fi
+                # Check that one key is not used to sign multiple times
+                if [[ ! " ${trusted_used[*]} " =~ " ${gpg_bash_lib_output_fingerprint_in_hex} " ]]; then
+                    echo "One of the trusted keys was verified."
+                    trusted_used+=($gpg_bash_lib_output_fingerprint_in_hex)
+                    trusted=$((trusted+1))
+                else
+                    echo "Verification failed: One of the trusted keys was used to sign multiple times."
+                    exit 1
+                fi
+            else
 
+                # Check that one key is not used to sign multiple times
+                if [[ ! " ${confirmed_used[*]} " =~ " ${gpg_bash_lib_output_fingerprint_in_hex} " ]]; then
+                    echo "One of the normal keys was verified."
+                    confirmed_used+=($gpg_bash_lib_output_fingerprint_in_hex)
+                    confirmed=$((confirmed+1))
+                else
+                    echo "Verification failed: One of the trusted keys was used to sign multiple times."
+                    exit 1
+                fi
+            fi
+        else
+            echo "Signature by key $gpg_bash_lib_output_fingerprint_in_hex could not be validated"
+        fi
+    fi
+    total=$((total+1))
     echo "$FUNCNAME: END"
 }
 
 
 bitcoind_decide() {
 
-    # TODO: Based on what keys were verified, give the final binary output here
-    echo "make decision here"
-    #number_of_hashes_in_trusted=count_somehow
-    # if trusted == number_of_hashes_in_trusted && confirmed >= bitcoin_min_confirm
+    # Check each of the specified trusted key hashes
+    for hash in "${bitcoind_trusted_key_hashes[@]}"
+    do
+        # And make sure that it exists in the array containing the verified hashes
+        if [[ ! " ${trusted_used[*]} " =~ " ${hash} " ]]; then
+            echo "Verification failed: One of the trusted signers keys ($hash) was not among the verified keys"
+            exit 1
+        fi
+    done
 
+    if [ "$confirmed" -ge "$bitcoind_min_confirm" ]; then
+
+        not_verified=$(($total-confirmed-trusted))
+
+        # Loop through the trusted keys and verify that each of them were actually used in the verification
+        echo "Verification successful"
+        echo "  $((confirmed+trusted))/$total signatures validated ($not_verified signatures could not be verified)"
+        echo "  Found valid signatures from all $trusted trusted keys"
+        echo "  In addition $confirmed valid signatures was found (minimum $bitcoind_min_confirm required)"
+        exit 0
+    else
+        echo "Verification failed: Could only confirm $confirmed signatures ($bitcoind_min_confirm required)"
+        exit 1
+    fi
 }
 
-
+# Run the script
 bitcoind_begin
 bitcoind_verification
 bitcoind_decide
